using System;
using System.Collections;
using System.ComponentModel;
using System.Drawing;
using System.Threading;
using System.Windows;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using Input = System.Windows.Input;

namespace BitmapConsole
{
    internal class ViewModel : INotifyPropertyChanged
    {
        public ViewModel()
        {
            Text = "AAAAAAAAAAD8AwYOAQgBCAEIDgf8AwAAAAAAANu2bdsAAAAAAAAAAAAADAAEAP8P/w8AAAAAAAAAAAAA27Zt2wAAAAAAAAAIBg4DD4ELgQnBCHcIHggAAAAAAADbtm3bAAAAAAAAAAAGBgMMIQghCDEI3gbMBwAAAAAAANu2bdsAAAAAAAAAAcABcAEYAQ4B/w8AAQABAAAAAAAA27Zt2wAAAAAAAAAAOAY/DBEIEQgRCHEG4QMAAAAAAADbtm3bAAAAAAAAAAD8A2YGEQgRCBEIdw7mBwAAAAAAANu2bdsAAAAAAAAAAAEAAQjBD/EBPQAHAAMAAAAAAAAA27Zt2wAAAAAAAAAA3gdzDCEIIQghCN4MzAcAAAAAAADbtm3bAAAAAAAAAAB+BscOgQiBCIEIZgb8AwAAAAAAANu2bdsAAAAAAAAAADAPmAmICIgIyAT4D+APAAAAAAAA27Zt2wAAAAAAAAAA/w84DggICAgICDgG8AMAAAAAAADbtm3bAAAAAAAAAADwBxgMCAgICAgIGAwQBAAAAADbtm3bAAAAAAAAgADwBxgMCAgICAgIMAb/DwAAAAAAANu2bdsAAAAAAAAAAPAHuAyICIgIiAiwDPAEAAAAAAAA27Zt2wAAAAAAAAAACAD/DwkACQAAANu2bdsAAAAAAADAAfAnGEwISAhICEgwNvg/AAAAAAAA27Zt2wAAAAAAAAAA/w//DwgACAAIABgA8A/ADwAAAADbtm3bAAAAAAAAAAD5D/kPAAAAANu2bdsAAAAAAEAAQPl/+R8AAAAA27Zt2wAAAAAAAAAA/w//D8AA8AEYBwgMCAgAAAAA27Zt2wAAAAAAAAAA/w//DwAAAADbtm3bAAAAAAAAAAD4D/gPCAAIABgA+A8wAAgACAAYAPgPAAAAAAAAAADbtm3bAAAAAAAAAAD4D/gPCAAIAAgAGADwD8APAAAAANu2bdsAAAAAAAAAAPAHGAwICAgICAg4BvAHAAAAAAAA27Zt2wAAAAAAAAAA+H84fggICAgICDgG8AMAAAAAAADbtm3bAAAAAAAAgADwBxgMCAgICAgIMA74fwAAAAAAANu2bdsAAAAAAAAAAPgP+A8IAAgAAAAAANu2bdsAAAAAAAAAAHAEyAjICIgImA0QBwAAAAAAANu2bdsAAAAAAAAIAP4P/w8ICAAAAADbtm3bAAAAAAAAAAD4B/gPAAgACAAIAAT4D/gPAAAAANu2bdsAAAAAAAAIAHgA4AMADwAP4AN4AAgAAAAAANu2bdsAAAAAAAAYAPgAgA8ADuADOAD4AYAPAA7gA3gAAAAAAAAA27Zt2wAAAAAAAAgIGAwwB+AB4AEwBxgMCAgAAAAA27Zt2wAAAAAAAAgAeEDgQQA/AA/gA3gACAAAAAAA27Zt2wAAAAAAAAAICA4IC4gJ6Ag4CBgIAAgAAAAA27Zt2wAAAAAAAAAMgAfgAbwAjwCDAJ4A8ADAAwAPAAgAAAAA27Zt2wAAAAAAAAAAAAD/DyEIIQghCCEIIQh/Ds4HAAAAAAAA27Zt2wAAAAAAAAAA+AH+BwIEAQgBCAEIAQgDDAYHBAMAAAAAAADbtm3bAAAAAAAAAAAAAP8PAQgBCAEIAQgBCAMMngf4AQAAAAAAANu2bdsAAAAAAAAAAAAA/w8hCCEIIQghCCEIIQgBCAAAAAAAANu2bdsAAAAAAAAAAAAA/w9BAEEAQQBBAEEAAQAAAAAAAADbtm3bAAAAAAAAAAD4AfwDAgQDDAEIAQhBCEMIRgTOB8ADAAAAAAAA27Zt2wAAAAAAAAAAAAD/DyAAIAAgACAAIAAgAP8PAAAAAAAAAADbtm3bAAAAAAAAAAAAAP8PAAAAAAAA27Zt2wAAAAAAAAABAAcADAAIAAz/BwAAAAAAAAAA27Zt2wAAAAAAAAAAAAD/D+AAYADwANgBjAMHBgMMAQgAAAAA27Zt2wAAAAAAAAAAAAD/DwAIAAgACAAIAAgACAAAAADbtm3bAAAAAAAAAAD/Dx8APgDwAIAHAA4AD+ABPAAPAP8PAAAAAAAAAADbtm3bAAAAAAAAAAAAAP8PDwAcADAA4ACAAwAP/w8AAAAAAAAAANu2bdsAAAAAAAAAAPgB/gMCBAEIAQgBCAEIAgQOB/wDAAAAAAAAAADbtm3bAAAAAAAAAAAAAP8PQQBBAEEAQQBBAH8APgAAAAAAAADbtm3bAAAAAAAAAAD8AQ4HAgQBCAEIAQoBDgMMBg78C+AQAAAAAAAA27Zt2wAAAAAAAAAAAAD/D0EAQQBBAMEAwQFjBz4OAAgAAAAAAADbtm3bAAAAAAAAAAAcBj4EIQghCGEIQQhDCMYHhAMAAAAAAADbtm3bAAAAAAAAAQABAAEAAQD/DwEAAQABAAEAAAAAAAAA27Zt2wAAAAAAAAAAAAD/AwAGAAgACAAIAAgABv8HAAAAAAAAAADbtm3bAAAAAAAAAQAPAHwA4AEADwAMgAfwAD4ABwABAAAAAADbtm3bAAAAAAAAAwAfAPgBgA8AD+ADPgAHAB8A+ACADwAO8AM/AAcAAAAAANu2bdsAAAAAAAAACAMMBweMA/gAcADYAQ4DAw4BCAAAAAAAANu2bdsAAAAAAAABAAMABgAcAHAA4A9wABgADgADAAEAAAAAANu2bdsAAAAAAAAACAEOAQvBCeEIMQgdCAcIAwgAAAAAAADbtm3bAAAAAAAAAAAwD5gJiAiICMgE+A/gDwAAAAAAANu2bdsAAAAAAAAAAP4HMgwJCAkICQg5DvEHAAAAAAAA27Zt2wAAAAAAAAAA+A/4D4gIiAiICPgPIAcAAAAAAADbtm3bAAAAAAAAAAD4D/gPCAAIAAgAAAAAANu2bdsAAAAAAAAAOAAO+A8ICAgICAj4DwA4AAAAAAAA27Zt2wAAAAAAAAAA8Ae4DIgIiAiICLAM8AQAAAAAAADbtm3bAAAAAAAAAADwB7oMigiICIoIsgzwBAAAAAAAANu2bdsAAAAAAAAICAgOcAPAAYAA+A+AAIABcAMYDggIAAAAANu2bdsAAAAAAAAABBgMCAiICNgIcA8AAgAAAADbtm3bAAAAAAAAAAD4D/gPAAeAAWAAOAD4DwAAAAAAANu2bdsAAAAAAAAAAPgP+A8DB4IBYgA7APgPAAAAAAAA27Zt2wAAAAAAAAAA+A/4D8ABcAMYDggIAAAAANu2bdsAAAAAAAAACPgP+AMIAAgACAD4D/gPAAAAAAAA27Zt2wAAAAAAAAAA+A/4D+AAAAcADsADeAD4D/gPAAAAAAAA27Zt2wAAAAAAAAAA+A/4D4AAgACAAPgP+A8AAAAAAADbtm3bAAAAAAAAAADwBxgMCAgICAgIOAbwBwAAAAAAANu2bdsAAAAAAAAAAPgP+A8IAAgACAD4D/gPAAAAAAAA27Zt2wAAAAAAAAAA+H84fggICAgICDgG8AMAAAAAAADbtm3bAAAAAAAAAADwBxgMCAgICAgIGAwQBAAAAADbtm3bAAAAAAAACAAIAAgA+A8IAAgACAAAAAAA27Zt2wAAAAAAAAgAeEDgQQA/AA/gA3gACAAAAAAA27Zt2wAAAAAAAAAA8AcYDAgICAgYDP9/GAwICAgIGAzwB8ABAAAAANu2bdsAAAAAAAAICBgMMAfgAeABMAcYDAgIAAAAANu2bdsAAAAAAAAAAPgP+A8ACAAIAAj4D/h/AHgAAAAA27Zt2wAAAAAAAPgA+AEAAQABAAH4D/gPAAAAAAAA27Zt2wAAAAAAAAAA+A/4DwAIAAj4D/gPAAgACAAI+A/4DwAAAAAAANu2bdsAAAAAAAAAAPgP+A8ACAAI+A/4DwAIAAgACPgP+H8AeAAAAADbtm3bAAAAAAAACAAIAAgA+A/4D4AIgAiACAAHAAIAAAAA27Zt2wAAAAAAAAAA+A/4D4AIgAiACIAPAAcAAPgP+A8AAAAAAADbtm3bAAAAAAAACAAIAAgA+A/4D4AIgAiACAAHAAIAAAAA27Zt2wAAAAAAACACMAYYCIgIiAiYDPAHgAEAAAAA27Zt2wAAAAAAAAAA+A/4D4AA4AMwBggICAgICBgM8AcAAAAAAADbtm3bAAAAAAAAAAhwDlgHiAGIAIgA+A/4DwAAAAAAANu2bdsAAAAAAAAADIAH4AG8AI8AgwCeAPAAwAMADwAIAAAAANu2bdsAAAAAAAAAAAAA/w8hCCEIIQghCCEI4QeAAwAAAAAAANu2bdsAAAAAAAAAAAAA/w8hCCEIIQghCCEIfw7OBwAAAAAAANu2bdsAAAAAAAAAAAAA/w8BAAEAAQABAAEAAQAAAAAA27Zt2wAAAAAAAAB4AA//DwEIAQgBCAEIAQj/DwB4AAAAAAAA27Zt2wAAAAAAAAAAAAD/DyEIIQghCCEIIQghCAEIAAAAAAAA27Zt2wAAAAAAAAAAAAD/DyEIIQghCCEIIQghCAEIAAAAAAAA27Zt2wAAAAAAAAEIAQ4HB94B2AAgACAA/w8gACAA2ADeAYcHAQ4BCAAAAADbtm3bAAAAAAAAAAAGBgMMAQghCCEIMwzeB4wDAAAAAAAA27Zt2wAAAAAAAAAAAAD/DwAPgAPAAHAAHAAHAP8PAAAAAAAAAADbtm3bAAAAAAAAAAAAAP8PAA+AA8AAcAAcAAcA/w8AAAAAAAAAANu2bdsAAAAAAAAAAP8PIAAgAHAA3AGHBwEOAQgAAAAA27Zt2wAAAAAAAAAIAAj/DwEAAQABAAEAAQD/DwAAAAAAAAAA27Zt2wAAAAAAAAAA/w8fAD4A8ACABwAOAA/gATwADwD/DwAAAAAAAAAA27Zt2wAAAAAAAAAAAAD/DyAAIAAgACAAIAAgAP8PAAAAAAAAAADbtm3bAAAAAAAAAAD4Af4DAgQBCAEIAQgBCAIEDgf8AwAAAAAAAAAA27Zt2wAAAAAAAAAAAAD/DwEAAQABAAEAAQABAP8PAAAAAAAAAADbtm3bAAAAAAAAAAAAAP8PQQBBAEEAQQBBAH8APgAAAAAAAADbtm3bAAAAAAAAAAD4Af4HAgQBCAEIAQgBCAMMBgcEAwAAAAAAANu2bdsAAAAAAAABAAEAAQABAP8PAQABAAEAAQAAAAAAAADbtm3bAAAAAAAAAQAHCBwIcAjgDoAD4AA4AA8AAwAAAAAA27Zt2wAAAAAAAAAA+ACYAQwDBAL/D/8PBAIEAggB+AFgAAAAAADbtm3bAAAAAAAAAAgDDAcHjAP4AHAA2AEOAwMOAQgAAAAAAADbtm3bAAAAAAAAAAAAAP8PAAgACAAIAAgACAAI/w8AeAAAAAAAANu2bdsAAAAAAAAAAH8A4ACAAIAAgACAAMAA/w8AAAAAAAAAANu2bdsAAAAAAAAAAAAA/w8ACAAIAAgACP8PAAgACAAIAAj/DwAAAAAAAAAA27Zt2wAAAAAAAAAAAAD/DwAIAAgACAAI/w8ACAAIAAgACP8PAHgAAAAAAADbtm3bAAAAAAAAAQABAAEAAQD/DyAIIAggCCAIIAhgDMAHAAAAAAAA27Zt2wAAAAAAAAAAAAD/DyAAIAD4AQ4HAgQBCAEIAQgBCAIE/gf4AQAAAAAAANu2bdsAAAAAAAAAAAAA/w8gCCAIIAggCCAIYAzABwAAAAAAANu2bdsAAAAAAAAAAAQCBgYDDAEIIQghCCEIIgS+B/gBAAAAAAAA27Zt2wAAAAAAAAAAAAD/DyAAIAD4AQ4HAgQBCAEIAQgBCAIE/gf4AQAAAAAAANu2bdsAAAAAAAAAAAAIPg5zB8EBwQBBAEEAQQD/DwAAAAAAAAAA27Zt2wAAAAAAAAAAAQADAAAAAAAAAAAA27Zt2wAAAAAAAAAAIAAgACAAYABAAEAAQAAgAAAAAADbtm3bAAAAAAAAAAD/C/8LAAAAAAAA27Zt2wAAAAAAAAAA4Ac4HAww4idybhlICUgJRBFP+U86SAYkDCb4EQAQAAAAAAAA27Zt2wAAAAAAABABEA/4AR8BEAGQD/gBFwEQAQAAAADbtm3bAAAAAAAAAAAeBjMMIQj/H2EIxg6EBwAAAAAAANu2bdsAAAAAAAAAAB4AMwAhCD8MHgPAADAAjAfDD0EIQAiABwAAAAAAANu2bdsAAAAAAAAgADgADgADAA4AOAAgAAAAAAAAANu2bdsAAAAAAAAAAIAHzgx/CHEI8QifDQ4HgAeADAAAAAAAANu2bdsAAAAAAAAAABIAHgAPABoAAgAAAAAA27Zt2wAAAAAAAAAA8Af8HwdwAUAAAAAA27Zt2wAAAAAAAAAAA2AOOPgPwAEAAAAA27Zt2wAAAAAAAAABAAEAAQABAAEAAAAA27Zt2wAAAAAAAABAAEAAQABAAEAAQABAAEAAQAAAAADbtm3bAAAAAAAAAABAAEAAQAD4A0AAQABAAEAAAAAAANu2bdsAAAAAAAAAABABEAEQARABEAEQARABEAEAAAAA27Zt2wAAAAAAAAAAEgAeAA8AGgACAAAAAADbtm3bAAAAAAAAAAAICAgIAAAAAAAA27Zt2wAAAAAAAAAACEgIOAAAAAAAANu2bdsAAAAAAAAAAA8AAAADAA8AAAAAAAAA27Zt2wAAAAAAAAAADwAAAAAAAADbtm3bAAAAAAAAAAAASAA4AAAAAAAA27Zt2wAAAAAAAAAAAAgACAAAAAAAANu2bdsAAAAAAAAAAEAAoACgAKAAEAEQAQgCCAIAAAAA27Zt2wAAAAAAAAAACAIQARABEAGgAKAAQABAAAAAAADbtm3bAAAAAAAAAAzAA3gABwAAAAAA27Zt2wAAAAAAAAEADwDwAIAPAAgAANu2bdsAAAAAAAAAAP9//38AAAAAAADbtm3bAAAAAAAAAAAAANu2bds=";
            BitmapHeight = 16;
        }

        private string _text;
        public string Text
        {
            get
            {
                return _text;
            }
            set
            {
                _text = value;
                OnPropertyChanged(nameof(Text));
            }
        }

        private int _bitmapHeight;
        public int BitmapHeight
        {
            get
            {
                return _bitmapHeight;
            }
            set
            {
                _bitmapHeight = value;
                OnPropertyChanged(nameof(BitmapHeight));
            }
        }

        private object _image;
        public object Image
        {
            get
            {
                return _image;
            }
            set
            {
                _image = value;
                OnPropertyChanged(nameof(Image));
            }
        }

        public event PropertyChangedEventHandler PropertyChanged;
        protected void OnPropertyChanged(string propertyName)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }


        private DelegateCommand _decodeBase64;
        public Input.ICommand DecodeBase64
        {
            get
            {
                if (_decodeBase64 == null)
                {
                    _decodeBase64 = new DelegateCommand((o) =>
                    {
                        var bytes = Convert.FromBase64String(Text);
                        var bits = new BitArray(bytes);

                        PixelFormat pf = PixelFormats.Bgr32;
                        int width = bits.Length / BitmapHeight;
                        int height = BitmapHeight;
                        int rawStride = (width * pf.BitsPerPixel + 7) / 8;
                        byte[] rawImage = new byte[rawStride * height];

                        var x = 0;
                        var y = 0;
                        for (int i = 0; i < bits.Length + 1; i++)
                        {
                            var bit = bits[i];
                            var rawIndex = (width * y + x) * 4;
                            rawImage[rawIndex + 2] = (byte)(bit ? 255 : 0);
                            //rawImage[rawIndex + 1] = (byte)(bit ? 255 : 0);
                            //rawImage[rawIndex + 2] = (byte)(bit ? 255 : 0);
                            y++;
                            if (y >= BitmapHeight)
                            {
                                y = 0;
                                x++;
                            }
                            if (x >= width)
                            {
                                break;
                            }
                        }
                        // Create a BitmapSource.
                        BitmapSource bitmap = BitmapSource.Create(width, height,
                            96, 96, pf, null,
                            rawImage, rawStride);
                        Image = bitmap;
                    });
                }
                return _decodeBase64;
            }
        }
    }
}